# Generated by Django 3.0.6 on 2020-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('photo_prem', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('price', models.IntegerField(verbose_name='Price-tag')),
            ],
        ),
    ]
